---
title: "WeightedBayes"
author: "Lasse Hyldig Hansen"
date: "2023-04-18"
output: html_document
---

### Loading packages

```{r}
pacman::p_load(
  tidyverse,
  brms,
  cmdstanr,
  patchwork
)
```

### Generating data

```{r}
WeightedBayes_f <- function(bias, Source1, Source2, w1, w2){
  w1 <- (w1 - 0.5)*2
  w2 <- (w2 - 0.5)*2
  outcome <- inv_logit_scaled(bias + w1 * logit_scaled(Source1) + w2 * logit_scaled(Source2))
  return(outcome)
}

WeightedBayes_f1 <- function(bias, Source1, Source2, w1, w2){
  outcome <- inv_logit_scaled(bias + weight_f(logit_scaled(Source1), w1) +
                                weight_f(logit_scaled(Source2), w2))
  return(outcome)
}

weight_f <- function(L, w){
  return(log((w * exp(L) + 1 - w) / 
        ((1 - w) * exp(L) + w)))
      }

bias <- 0
trials <- 1000
n_participants <- 10
feedback = c(-3, -2, 0, 2, 3)
w1 = 0.8
w2 = 0.7

Source_df <- data.frame()


  
for (t in 1:max(trials)){
    
    Source1 = sample(1:8, 1, replace = T)
    Source2 = Source1 + sample(feedback, 1)
    Trial = t
    Bias = bias
    w1 = w1
    w2 = w2
    
  
    while (!(Source2 %in% c(1:8))) {
          Source2 = Source1 + sample(feedback, 1)
      }
  
  Source_Vector = c(Source1, Source2, Trial, Bias, w1, w2)
      
  Source_df <- rbind(Source_df, Source_Vector)
  colnames(Source_df) <- c("Source1", "Source2", "Trial", "bias", "w1", "w2")
  
  }
  

for (n in seq(nrow(Source_df))) {
  
  Source_df$Source1[n] <- Source_df$Source1[n]/9
  Source_df$Source2[n] <- Source_df$Source2[n]/9
  
  Source_df$belief[n] <- WeightedBayes_f(Source_df$bias[n], 
                                         Source_df$Source1[n], 
                                         Source_df$Source2[n],
                                         Source_df$w1[n], 
                                         Source_df$w2[n])
  
  Source_df$belief1[n] <- WeightedBayes_f1(Source_df$bias[n], 
                                         Source_df$Source1[n], 
                                         Source_df$Source2[n],
                                         Source_df$w1[n], 
                                         Source_df$w2[n])
  
  Source_df$discrete[n] <- round(Source_df$belief[n] * 9, 0)

  Source_df$discrete[n] <- ifelse(Source_df$discrete[n] == 9, 8,
                           ifelse(Source_df$discrete[n] == 0, 1, Source_df$discrete[n]))
  
  Source_df$discrete1[n] <- round(Source_df$belief1[n] * 9, 0)

  Source_df$discrete1[n] <- ifelse(Source_df$discrete1[n] == 9, 8,
                           ifelse(Source_df$discrete1[n] == 0, 1, Source_df$discrete[n]))
  
  
}
```


### Making sanity check visualizations

```{r}
ggplot(Source_df, aes(belief, belief1)) +
  geom_point() +
  theme_bw()
```

```{r}
ggplot(Source_df) +
  geom_histogram(aes(belief), bins = 10, alpha = 0.3, color = "black", fill = "red") +
  geom_histogram(aes(belief1), bins = 10, alpha = 0.3, color = "black", fill = "blue") +
  theme_bw()
```

```{r}
p1 <- ggplot(Source_df, aes(Source1, belief, color = Source2, group = Source2)) +
  geom_line() +
  theme_bw() +
  facet_wrap(w1~w2)
p1
```

### Creating stan model


```{r}
stan_WB_model <- "
data {
  int<lower=0> N;
  array[N] real <lower = 0, upper = 1> y;
  array[N] real <lower = 0, upper = 1> Source1; 
  array[N] real <lower = 0, upper = 1> Source2; 
}

transformed data {
  array[N] real l_Source1;
  array[N] real l_Source2;
  array[N] real l_Discrete_Choice;
  l_Source1 = logit(Source1);
  l_Source2 = logit(Source2);
  l_Discrete_Choice = logit(y);
}
parameters {
  real bias;
  real<lower = 0.0001> sd;
  // meaningful weights are btw 0.5 and 1 (theory reasons)
  real<lower = 0.5, upper = 1> w1; 
  real<lower = 0.5, upper = 1> w2;
}
transformed parameters {
  real<lower = 0, upper = 1> weight1;
  real<lower = 0, upper = 1> weight2;
  // weight parameters are rescaled to be on a 0-1 scale (0 -> no effects; 1 -> face value)
  weight1 = (w1 - 0.5) * 2;  
  weight2 = (w2 - 0.5) * 2;
}
model {

  target += normal_lpdf(bias | 0, 0.5);
  target += beta_lpdf(weight1 | 2, 2);
  target += beta_lpdf(weight2 | 2, 2);
  target += lognormal_lpdf(sd | 0, 0.5);
  
  target += normal_lpdf(to_vector(l_Discrete_Choice) | bias + weight1 * to_vector(l_Source1) + weight2 * to_vector(l_Source2), sd);

}

generated quantities{
  array[N] real log_lik;
  real bias_prior;
  real sd_prior;
  real w1_prior;
  real w2_prior;
  bias_prior = normal_rng(0, 0.5) ;
  sd_prior = lognormal_rng(0, 0.5);
  w1_prior = 0.5 + inv_logit(normal_rng(0, 1))/2 ;
  w2_prior = 0.5 + inv_logit(normal_rng(0, 1))/2 ;
  for (n in 1:N)
    log_lik[n]= normal_lpdf(l_Discrete_Choice[n] | bias + weight1 * l_Source1[n] + weight2 * l_Source2[n], sd);
}

"

write_stan_file(
  stan_WB_model,
  dir = "stan/",
  basename = "W9_WB.stan")
```

### Loading stan model

```{r}
file <- file.path("stan/W9_WB.stan")
mod_wb <- cmdstan_model(file, cpp_options = list(stan_threads = TRUE),
                     stanc_options = list("O1"))
```

### Getting data for stan and sampling model

```{r}
data_weightedBayes <- list(
  N = nrow(Source_df),
  y = Source_df$discrete/9,
  Source1 = Source_df$Source1,
  Source2 = Source_df$Source2
)

samples_weighted <- mod_wb$sample(
  data = data_weightedBayes,
  seed = 123,
  chains = 2,
  parallel_chains = 2,
  threads_per_chain = 2,
  iter_warmup = 1500,
  iter_sampling = 3000,
  refresh = 500
)
```
### Model diagnostics

```{r}
samples_weighted$cmdstan_diagnose()
```

### Model summary

```{r}
samples_weighted$summary()
```
### Model LOO

```{r}
samples_weighted$loo()
```
### Trace plots


```{r}
draws_df <- as_draws_df(samples_weighted$draws())

ggplot(draws_df, aes(.iteration, bias, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()
```

```{r}
ggplot(draws_df, aes(.iteration, w1, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()
```

```{r}
ggplot(draws_df, aes(.iteration, w2, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()
```

### Prior/Posterior plots

```{r}
p1 <- ggplot(draws_df) +
  geom_density(aes(bias), alpha = 0.6, fill = "lightblue") +
  geom_density(aes(bias_prior), alpha = 0.6, fill = "pink") +
  geom_vline(xintercept = Source_df$bias[1]) +
  theme_bw()

p2 <- ggplot(draws_df) +
  geom_density(aes(w1), alpha = 0.6, fill = "lightblue") +
  geom_density(aes(w1_prior), alpha = 0.6, fill = "pink") +
  geom_vline(xintercept = 0.8) +
  theme_bw()

p3 <- ggplot(draws_df) +
  geom_density(aes(w2), alpha = 0.6, fill = "lightblue") +
  geom_density(aes(w2_prior), alpha = 0.6, fill = "pink") +
  geom_vline(xintercept = 0.7) +
  theme_bw()

p1 + p2 + p3
```



